import { Injectable, OnInit } from '@angular/core';
import { first, map } from 'rxjs';
import { GeocodeService } from '../geocode/geocode.service';

@Injectable({
  providedIn: 'root',
})
export class BulkRequestHandler {
  constructor(private readonly _service: GeocodeService) {}

  // async hello(): Promise<void> {
  public _hello(): void {
    const y = [
      'Newmarket Town Cemetery, High Street, Newmarket, Suffolk',
      'All Saints Churchyard, Clayton-le-Moors, Hyndburn, Lancashire BB5 5HT.',
      'Chadderton Cemetery10, 624-636 Middleton Road, Oldham OL9 0JZ',
      'Bath, Somerset. Cremated.',
      "St. Mary's Churchyard, Leighton Linslade, Bedfordshire",
      'Metairie Cemetery, 5100 Pontchartrain Blvd., New Orleans, Louisiana, USA',
      'Layton Cemetery, Blackpool, Lancashire FY3 7BD',
      'Liverpool Road Cemetery, Liverpool Road, Birkdale, Merseyside, PR8 3BD',
      'Edenbridge, Kent. Cremated.',
      'Sale Brooklands Cemetery,Marsland Road, Brooklands, Sale, Cheshire M33 7UN',
      'Macquarie Park Cemetery and Crematorium, North Ryde, Ryde City, New South Wales, Australia',
      'Barrow-In-Furness Cemetery, Devonshire Road, Barrow-In-Furness, Cumbria, LA14 5PD',
      'Christ Church Churchyard, Esher, Surrey.',
      'Broadstone Cemetery, Broadstone, Dorset',
      'St John the Evangelist Churchyard, Dormansland, Surrey',
      'Burnley Cemetery, Cemetery Lane off Rossendale Road, Burnley',
      'Fifield Manor, Oxford. Cremated.',
      'Blackley Crematorium.',
      'Preston New Cemetery, Ribbleton, Lancashire',
      "St. Julian's Churchyard, Rectory Road, Shoreham-by-Sea, West Sussex, BN43 6EB",
      "Saint Andrew's Churchyard, Leyland, Lancashire",
      'Burnley Cemetery, Cemetery Lane off Rossendale Road, Burnley',
      "St Martin's Church, Bowness, Cumbia. Buried in Bowness-on-Windermere Cemetery, LA23 3HB.34",
      "St. Peter's Churchyard, Brackley, Northamptonshire",
      'West Lancashire Crematorium, Burscough, Lancashire.',
      'St Thomas Churchyard, Thurlbear, Somerset, TA3 5BW',
      'Manchester Crematorium',
      'Burnley Cemetery, Cemetery Lane off Rossendale Road, Burnley',
      'Southern Cemetery, 212 Barlow Moor Road, Chorlton-Cum-Hardy, Manchester, M21 7GL',
      "St. Mary's Churchyard, Church Lane, Mellor, Lancashire, BB2 7JL",
      'St. John the Evangelist Churchyard, Nelson, Lancashire',
      'Highland Road Cemetery36, Southsea, Hampshire.',
      'Cementerio Inglés, Las Palmas de Gran Canaria, Islas Canarias, Spain',
      'St. John the Evangelist Churchyard, Worsthorne, Lancashire, BB10 3NN',
      'Riem Airport, near Munich, Germany. Cremated at Manchester Crematorium.',
      "St Joseph's Roman Catholic Cemetery, Monks Kirby, Warwickshire.",
      'Southern Cemetery & Crematorium7 A60 Loughborough Road, West Bridgford, Nottinghamshire, NG2 7FE',
      "St. Bartholomew's Churchyard, Huyton with Roby, Knowsley, Merseyside",
      'Warrington Parish Churh. Cremated at Walton Lea Crematorium. Ashes scattered in Garden of Remembrance.34',
      'Anfield Cemetery, Anfield, Liverpool L4 2SL.',
      'St. Lawrence Churchyard, Barton, Preston, Lancashire',
      "St. Bartholomew's Churchyard, Huyton with Roby, Knowsley, Merseyside",
      'Tyldesley Cemetery, Tyldesley, Greater Manchester. Memorial at Old Trafford Cricket Ground.',
      'Sutton Coldfield crematorium, Warwickshire',
      'St Mary the Virgin Churchyard, Stamford Road, Bowdon, Cheshire WA14 2TR. (Plot No. 2976A)',
      'St. Mary and the Holy Cross Churchyard, Frinsted Road, Milstead, Kent',
      'Burnley Cemetery, Cemetery Lane off Rossendale Road, Burnley',
      'St James Churchyard, Didsbury, Manchester',
      'Marcoing, Cambrai, France. Buried or commemorated at Cambrai Memorial, Louveral.9',
      'Rochdale Crematorium, Lancashire',
      'Brookfield Unitarian Churchyard, Gorton, Manchester',
      'Chadderton Cemetery10, 624-636 Middleton Road, Oldham OL9 0JZ',
      'St John the Baptist Churchyard, Bollington, Cheshire',
      'Loughborough Cemetery, Leicester Road, Loughborough LE11 2AF',
      "St Michael's Church, Great Lever, Lancashire.34",
      'Christ Church Churchyard, Harwood, Bolton.',
      'Tonge Cemetery39, Bolton, BL2 6AQ.',
      'Rosser Manitoba11. Buried at Saint Michaels Anglican Church Cemetery,Grosse Isle, Manitoba, Canada',
      'Vadencourt British Cemetery, Maissemy, France12',
      'Christ Church, Timperley, Cheshire.',
      'Toxteth Park Cemetery13, 124 Smithdown Road, Liverpool L15 2HD',
      "St. Peter's Churchyard, Rowley, East Riding of Yorkshire",
      'Gore Hill Cemetery, St Leonards,Sydney, New South Wales, Australia',
      'Northwood Cemetary, Union Road, Cowes, Isle of Wight',
      'Carmountside Cemetery and Crematorium, Milton, Stoke-on-Trent, Staffordshire ST2 7AB.',
      'Rochdale Cemetery and Crematorium, Rochdale, Lancashire',
      'Denton Cemetery, Denton, Tameside M34 6ER',
      'St Mary Churchyard, Acton, Cheshire CW5 8LE',
      'Milverton Cemetery, Old Milverton Road, Leamington Spa, Warwickshire',
      'Springvale Botanical Cemetery40, Springvale, Greater Dandenong City, Victoria, Australia.',
      'All Saints Churchyard, Emberton, Milton Keynes, Buckinghamshire.',
      'York Old Cemetery.',
      'Southern Cemetery, 212 Barlow Moor Road, Chorlton-Cum-Hardy, Manchester, M21 7GL',
      'Saint Andrews Churchyard, Leyland, Lancashire PR25 3EL',
      'Audley Methodist Cemetery, Bignall End, Staffordshire ST7 8QE.34',
      'Southern Cemetery, 212 Barlow Moor Road, Chorlton-Cum-Hardy, Manchester, M21 7GL',
      'Overton churchyard, Flintshire, Wales',
      'Wolvercote Cemetery, Banbury Road, Oxford',
      'Carmountside Cemetery, Milton, Stoke-on-Trent, Staffordshire ST2 7AB',
      'Rochdale Cemetery and Crematorium',
      'Burnley Cemetery, Cemetery Lane off Rossendale Road, Burnley.',
      'St. Nicholas Churchyard, Halewood, Merseyside.',
      "St Mary's Churchyard, Church Lane, Wistaston, Cheshire, CW2 8HA",
      'All Saints Churchyard annexe, Claypit Lane, Ledsham, West Yorkshire, LS25 5LR',
      'St. Mary the Virgin Churchyard, Ivinghoe, Buckinghamshire',
      'St Mary the Virgin Churchyard, Church Lane, Send, Guildford, Surrey',
      "St. Bartholomew's Churchyard, Huyton with Roby, Merseyside",
      'Killyman St. Andrew Church of Ireland Churchyard, Dungannon, County Tyrone, Northern Ireland',
      'Taunton Deane Crematorium, Wellington New Road, Taunton,  Somerset',
      'Fareham Cemetery41, Wickham Road, Fareham, Hampshire PO16 7HX',
      'St Michael the Archangel Churchyard, Warfield, Berkshire RG42 6EG',
      'Bexhill Cemetery, Bexhill-on-Sea, East Sussex, TN39 5HT',
      'Salisbury Crematorium, 1 Barrington Rd, Salisbury, Wiltshire, SP1 3JB',
      'Preston New Cemetery, Ribbleton, Lancashire',
      "St Peter's Church, Streatham. Buried at St Mary's Church, Cotesbach, Leicestershire LE17 4HX.34",
      'Bangkok, Thailand. Buried at St Mary and St Nicholas Churchyard, Leatherhead, Surrey',
      'Layton Cemetery, Blackpool, FY3 7BD. Ashes interred in wall niche under Columbarium. 34',
      'All Saints Churchyard, Habergham Eaves, Burnley, Lancashire.',
      'Greenacres Cemetery, Greenacres Rd, Oldham, OL4 3HT',
      'Southern Cemetery, 212 Barlow Moor Road, Chorlton-Cum-Hardy, Manchester, M21 7GL',
      'All Saints Churchyard, Middleton Cheney, Northamptonshire OX17 2NR',
      'Philips Park Cemetery, Riverpark Road (off Briscoe Lane), Miles Platting, Manchester, M10 6XQ',
      'Holy Saviour Churchyard, Milbourne, Northumberland',
      'All Saints Churchyard, Oving, Buckinghamshire',
      'Tyne Cot Cemetery, Passchendaele, Arrondissement Ieper, West Flanders (West-Vlaanderen), Belgium',
      "St Mary's Churchyard, Kelbrook, Pendle, Lancashire",
      'Southern Cemetery, 212 Barlow Moor Road, Chorlton-Cum-Hardy, Manchester, M21 7GL',
      'Stockport Cemetery and Crematorium, Buxton Road, Heaviley, Stockport, SK2 6LS',
      'Allerton Cemetery, Woolton Road, Allerton, Liverpool L19 5NF',
      'St Andrew Churchyard, South Warnborough, Hampshire RG29 1RS',
      'Sale Brooklands Cemetery,Marsland Road, Brooklands, Sale, Cheshire M33 7UN',
      'Rawtenstall Cemetery, Lancashire BB4 8EW.34',
      'South Head Cemetery, 763 Old South Head Rd, Vaucluse, New South Wales 2030, Australia',
      'Westhoughton Cemetery, Westhoughton, Bolton BL5 2BG, England',
      'Toxteth Park Cemetery13, 124 Smithdown Road, Liverpool L15 2HD',
      'Dukinfield Cemetery and Crematorium, Hall Green Road, Dukinfield, SK16 4EP',
      'Philips Park Cemetery, Riverpark Road (off Briscoe Lane), Miles Platting, Manchester, M10 6XQ',
      'South Head Cemetery, 763 Old South Head Rd, Vaucluse, New South Wales 2030, Australia',
      'Southern Cemetery, 212 Barlow Moor Road, Chorlton-Cum-Hardy, Manchester, M21 7GL',
      'Sale Brooklands Cemetery,Marsland Road, Brooklands, Sale, Cheshire M33 7UN',
      'Frankston Cemetery, 63 Cranbourne Road, Frankston, Victoria 3199 Australia.',
      'Toxteth Park Cemetery13, 124 Smithdown Road, Liverpool L15 2HD',
      'Charlton Cemetery, Dover, Kent',
      'St John the Evangelist Churchyard, Stanmore, Harrow, London HA7 2QX',
      'Duke Street Cemetery, Southport, PR8 5EL',
      'Heaton Cemetery, Gilnow Road, Bolton, Lancashire BL1 4LH',
      'Cheriton Road Cemetery24, Folkestone, Kent',
      'All Saints Churchyard, Childwall, Liverpool L16 5EY',
      'Sutton Cemetery42, Lammas Road, Sutton-in-Ashfield, Nottinghamshire NG17 2ED',
      'Christ Church Churchyard, Cheshire Road, Woodford, SK7 1PR',
      'Barrow Cemetery and Crematorium25, Devonshire Road, Barrow-In-Furness, Cumbria, LA14 5PD',
      'Glossop Cemetery, Cemetery Road, Glossop, Derbyshire',
      'Harehills Cemetery, Kimberley Lane, Leeds, LS9 6LZ27',
      'Astwood Cemetery28, Astwood Road, Worcester, WR3 8HA',
      'Woodhall Spa Cemetery, Kirkby Lane, Woodall Spa, Lincolnshire LN10 6YZ',
      'West Lancashire Crematorium, Pippin Street,Ormskirk. L40 7SP',
      'Nakuru North Cemetery, Kenya',
      'Nakuru North Cemetery, Kenya',
      'Manchester Crematorium. Ashes interred at at Mill Lane Cemetery, Cheadle, Stockport SK8 2PX',
      'Kensal Green Cemetery2, Royal Borough of Kensington and Chelsea, London W10 4RA',
      'Toxteth Park Cemetery13, 124 Smithdown Road, Liverpool L15 2HD',
      'Toxteth Park Cemetery13, 124 Smithdown Road, Liverpool L15 2HD',
      'Toxteth Park Cemetery13, 124 Smithdown Road, Liverpool L15 2HD',
      'Southern Cemetery, 212 Barlow Moor Road, Chorlton-Cum-Hardy, Manchester, M21 7GL',
      'St Luke Churchyard, Great Crosby, Sefton, Merseyside L23 5SE',
      'Mossley Cemetery, Cemetery Rd, Mossley',
      'Duke Street Cemetery, Southport, PR8 5EL',
      'Rochdale Cemetery, Rochdale, Lancashire',
      'Bolton Cemetery30, Eden Street, Astley Bridge, BL1 6NU',
      'All Saints Churchyard, Thornton Hough, Metropolitan Borough of Wirral, Merseyside',
      'Rookwood General Cemetery31, Hawthorne Ave, Rookwood, New South Wales, 2141 Australia',
      "Saint Michael's Churchyard43, 1 Inveresk Village, Inveresk, East Lothian, Scotland EH21 7UA",
      'St Mark Churchyard, Worsley Brow, Worsley, Salford, Lancashire M28 2WH, England',
      'Westhoughton Cemetery, Westhoughton, Bolton BL5 2BG, England',
      'Westhoughton Cemetery, Westhoughton, Bolton BL5 2BG, England',
      'St Mark Churchyard, Worsley Brow, Worsley, Salford, Lancashire M28 2WH, England',
      "St Bartholomew's Churchyard, Westhoughton, Bolton BL5 2BG.34",
      'La Clytte Military Cemetery, De Klijte, West Flanders (West-Vlaanderen), Belgium',
      'Warrington Cemetery,32 Manchester Road, Warrington, Cheshire',
      'St. Laurence Churchyard, Tidmarsh, Berkshire',
      'Duke Street Cemetery, Southport, PR8 5EL',
      'Lower Ince Cemetery33, Cemetery Road, off Warrington Road, Ince in Makerfield, Wigan',
      'Duke Street Cemetery, Southport, PR8 5EL',
      'Glossop Cemetery, Cemetery Road, Glossop, Derbyshire',
      'Heaton Cemetery, Gilnow Road, Bolton, Lancashire BL1 4LH.',
      'Southern Cemetery, 212 Barlow Moor Road, Chorlton-Cum-Hardy, Manchester, M21 7GL',
      'Southern Cemetery, 212 Barlow Moor Road, Chorlton-Cum-Hardy, Manchester, M21 7GL',
      'Philips Park Cemetery, Riverpark Road (off Briscoe Lane), Miles Platting, Manchester, M10 6XQ',
      'Manchester Crematorium, Barlow Moor Rd, Manchester M21 7GZ',
      'Great Harwood Cemetery, Blackburn Road, Great Harwood, Lancashire',
      'St Philip and St James Escot Church, Ottery St Mary, Devon',
      'Manly Cemetery, Griffiths Street, Manly, New South Wales 2094, Australia',
      'Barly French Military Cemetery, Barly, Nord-Pas-de-Calais, France',
      'Ocklynge Cemetery, Willingdon Road, Eastbourne, Sussex BN21 1TL',
      'Duke Street Cemetery, Southport, PR8 5EL',
    ];

    const names = [
      'Jerry Ainsworth',
      'Arthur Appleby',
      'John Ashworth',
      'Graham Atkinson',
      'George Baker',
      'Gerald Bardswell',
      'Richard Barlow',
      'Frederick Baucher',
      'Arthur Baxter',
      'Charles Benton',
      'George Biddolph',
      'George Bigg',
      'George Bird',
      'Morice Bird',
      'Francis Birley',
      'Wilfred Blake20',
      'Robert Boddington',
      'John Bond',
      'Brian Booth',
      'Frank Booth',
      'Kenneth Bowling',
      'Richard Boys',
      'Walter Brearley',
      'George Campbell',
      'Ian Cockbain',
      'Terence Cole',
      'Roy Collins',
      'William Cook',
      'Samuel Corlett',
      'Josiah Coulthurst',
      'Frederick Crabtree',
      'Frederick Crooke',
      'Sydney Crosfield',
      'Henry Cudworth',
      'Harry Davies',
      'Charles De Trafford',
      'Thomas Dickinson',
      'Percy Dobell',
      'George Duckworth',
      'Arthur Durandu',
      'Alexander Eccles',
      'Henry Eccles',
      'Peter Eckersley',
      'James Edmonds',
      'Hubert Farrar',
      'William Findlay',
      'Ian Folley',
      'Frederick Gaddum',
      'Harold Garnett',
      'Thomas Greenhough',
      'George Grimshaw',
      'Stell Haggas',
      'Charles Haigh',
      'Albert Hallam',
      'Charles Hallows',
      'Frank Hardcastle',
      'Walter Hardcastle',
      'George Harper',
      'Alfred Hartley',
      'George Hartley',
      'Henry Hibbard',
      'Lyonel Hildyard',
      'Rowland Hill14',
      'John Hillkirk',
      'Gordon Hodgson',
      'Edwin Holroyd',
      'John Hopwood',
      'Albert Hornby',
      'Cecil Hornby',
      'William Horrocks',
      'Campbell Hulton',
      'Roger Iddison',
      'William Iddison',
      'John Iddon',
      'John Ikin',
      'Frederic Isherwood',
      'Edward Jackson',
      'Henry John',
      'William Jolley',
      'George Kemp16',
      'John Kershaw',
      'Edward Kewley',
      'Arthur Knowles',
      'Charles Landon',
      'William Leach',
      'Joseph Leese',
      'Edwin Leventon',
      'Richard Lloyd',
      'James Lomax',
      'Donald MacKinnon',
      'Archibald MacLaren',
      'Geoffrey MacLaren',
      'James MacLaren',
      'Walter Marchbank',
      'Charles17 Marriott',
      'Dudley Matthews',
      'Edgar McDonald8',
      'John Melling',
      'Josiah Mills',
      'Walter Mills',
      'Arthur Mold',
      'Edward Moorhouse',
      'Ralph Mortimer',
      'George Nash',
      'John Nelson',
      'Ezra Nutter',
      'William Openshaw',
      'Reginald Parkin',
      'Henry Parr',
      'Charles Pilkington',
      'Richard Pilling',
      'Winston Place',
      'Leslie Poidevin8',
      'Richard Pollard',
      'Thomas Potter',
      'George Radcliffe',
      'Lees Radcliffe',
      'Elisha Rawlinson',
      'Frederick Reynolds',
      'James Ricketts',
      'William Rickman',
      'Edward Roper',
      'Alexander Rowley',
      'Vernon Royle',
      'Charles Sawyer',
      'William Scott',
      'Alfred Seymour',
      'John Sharp',
      'Charles Shore',
      'Frank Sibbles',
      'Arthur Sladen',
      'Alfort Smith',
      'Charles Smith',
      'John Smith',
      'Reginald Spooner',
      'Kenneth Standring',
      'Henry Stanning',
      'John Stanning',
      'John Statham',
      'Allan Steel',
      'Ernest Steel',
      'Harold Steel',
      'Wilfred Stoddart',
      'Enoch Storer',
      'Frank Sugg',
      'John Sullivan',
      'Samuel Swire',
      'Frank Taylor',
      'Kevan Tebay',
      'Alfred Teggin',
      'Sidney Tindall',
      'Alfred Tinsley',
      'George Tyldesley',
      'Harry Tyldesley',
      'James Tyldesley',
      'John Tyldesley',
      'Richard Tyldesley',
      'William Tyldesley',
      'James Unsworth',
      'Roger Walker',
      'Henry Wall',
      'Thomas Wall',
      'William Wall',
      'Matthew Walton',
      'Albert Ward',
      'Alexander Watson',
      'Sidney Webb',
      'Thomas Whatmough',
      'Thomas Whitehead',
      'David Whittaker',
      'George Winder',
      'Reginald Wood',
      'Egerton Wright',
      'Frank Wright',
      'Calvert Yates',
    ];

    const t: Result[] = [];

    for (let index = 0; index < y.length; index++) {
      // await this._service
      this._service
        .geocode(y[index])
        .pipe(
          first(),
          // map(i => i.)
        ) //takeUntil(this._subscription))
        .subscribe({
          next: (r: any) => {
            // change any
            let u = new Result(
              names[index],
              y[index],
              r.results[0].geometry.location.lat,
              r.results[0].geometry.location.lng,
            );
            t.push(u);
            // this._addMarker(r.results[0].geometry.location.lat, r.results[0].geometry.location.lng); // false to stop second hit on API to get address...
          },
          error: () => {
            return null;
            //this.error = true;
          },
        });

      // const element = array[index];
    }

    console.log(t);
  }

  // jimmy(): void {
  //   const t: Results[] = [];
  // }
}

export class Result {
  private _name: string;
  private _lat: number;
  private _lng: number;
  private _address: string;

  public constructor(name: string, address: string, lat: number, lng: number) {
    this._name = name;
    this._lat = lat;
    this._lng = lng;
    this._address = address;
  }
}
